# Generated by Django 2.2 on 2019-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190413_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isGuest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
        ),
    ]
